// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhVhnjElEbc9aCJeAMU93dLdjfQl1iv64',
    appId: '1:342515837813:web:e4bb148f1928739139813c',
    messagingSenderId: '342515837813',
    projectId: 'bus-tracking-app-cc700',
    authDomain: 'bus-tracking-app-cc700.firebaseapp.com',
    storageBucket: 'bus-tracking-app-cc700.appspot.com',
    measurementId: 'G-LL6QG5TX0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9YJntauYc0HlLIHv0KgMkITiyO5M8hzU',
    appId: '1:342515837813:android:d0ce472d863b680239813c',
    messagingSenderId: '342515837813',
    projectId: 'bus-tracking-app-cc700',
    storageBucket: 'bus-tracking-app-cc700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvklwYswBxuvsXvfNF8bafqGxMM0o320',
    appId: '1:342515837813:ios:5082f9e82907fa1f39813c',
    messagingSenderId: '342515837813',
    projectId: 'bus-tracking-app-cc700',
    storageBucket: 'bus-tracking-app-cc700.appspot.com',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEvklwYswBxuvsXvfNF8bafqGxMM0o320',
    appId: '1:342515837813:ios:5082f9e82907fa1f39813c',
    messagingSenderId: '342515837813',
    projectId: 'bus-tracking-app-cc700',
    storageBucket: 'bus-tracking-app-cc700.appspot.com',
    iosBundleId: 'com.example.busTrackingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhVhnjElEbc9aCJeAMU93dLdjfQl1iv64',
    appId: '1:342515837813:web:b59f9a35a1458cbb39813c',
    messagingSenderId: '342515837813',
    projectId: 'bus-tracking-app-cc700',
    authDomain: 'bus-tracking-app-cc700.firebaseapp.com',
    storageBucket: 'bus-tracking-app-cc700.appspot.com',
    measurementId: 'G-HGK7TX5L8R',
  );
}
