name: bus_tracking_system
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_database: ^10.2.2
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.5.2
  shared_preferences: ^2.0.17
  flutter_map: ^5.0.0
  geolocator: ^9.0.2
  latlong2: ^0.9.0
  http: ^1.0.0
  app_settings: ^4.2.0
  flutter_local_notifications: ^14.0.0
  google_maps_flutter: ^2.5.3
  flutter: 
    sdk: flutter
  lottie: ^3.1.2
  flutter_polyline_points: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

